### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by yukixz** [poooi/plugin-battle-detail#3]
This is the roadmap of battle-detail.

## Version 1.1.0
- [x] Support showing battle detail of combined fleet.
- [x] Support using Damage Control in battle simulator.
- [x] Differ zero damage from miss. (Need to modify common.coffee:class Attack)
- [x] Standardize variable and function name in simulator.

## Version 1.2.0
- [x] Add 'Battle Information' Panel showing formation,air control, etc.

## Version ???
- [ ] Show fleet organization and equipment on Battle Information panel.

## Future
- [x] Write a document describing poi battle packet format in order to exchange data with other kancolle tools.
- [ ] Contains support fleet organization and equipment.

**Comment by yukixz** [comment]
On the fly.
